// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: game.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allGames = `-- name: AllGames :many
select game.id, game.created_at, game.updated_at, game.developer_id, game.slug, developer.slug as developer_slug
from game
     join developer on game.developer_id = developer.id
`

type AllGamesRow struct {
	ID            int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeveloperID   int32
	Slug          string
	DeveloperSlug string
}

func (q *Queries) AllGames(ctx context.Context) ([]AllGamesRow, error) {
	rows, err := q.db.Query(ctx, allGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllGamesRow
	for rows.Next() {
		var i AllGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeveloperID,
			&i.Slug,
			&i.DeveloperSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGameBySlug = `-- name: FindGameBySlug :one
select game.id, game.created_at, game.updated_at, game.developer_id, game.slug
from game
     join developer on game.developer_id = developer.id
where game.slug = $1 and developer.slug = $2
`

type FindGameBySlugParams struct {
	GameSlug string
	DevSlug  string
}

func (q *Queries) FindGameBySlug(ctx context.Context, arg FindGameBySlugParams) (Game, error) {
	row := q.db.QueryRow(ctx, findGameBySlug, arg.GameSlug, arg.DevSlug)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeveloperID,
		&i.Slug,
	)
	return i, err
}

const getGameAchievements = `-- name: GetGameAchievements :many
select id, created_at, updated_at, game_id, slug, name, description, progress_requirement from achievement where game_id = $1
`

func (q *Queries) GetGameAchievements(ctx context.Context, gameID int32) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getGameAchievements, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GameID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ProgressRequirement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
