// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID                  int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	GameID              int32
	Slug                string
	Name                string
	Description         string
	ProgressRequirement int32
}

type AchievementProgress struct {
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	UserID        int32
	AchievementID int32
	Progress      int32
}

type DeletedRecord struct {
	ID          pgtype.UUID
	DeletedAt   pgtype.Timestamptz
	SourceTable string
	SourceID    string
	Data        []byte
}

type Developer struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Slug      string
}

type DeveloperDisplayName struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	DeveloperID int32
	DisplayName string
}

type DeveloperMember struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	UserID      int32
	DeveloperID int32
}

type DeveloperSlugHistory struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	DeveloperID int32
	Slug        string
}

type Game struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeveloperID int32
	Slug        string
}

type GameSession struct {
	ID          pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	TokenID     pgtype.UUID
	LastPulseAt pgtype.Timestamptz
	GameID      int32
	UserID      int32
}

type Token struct {
	ID        pgtype.UUID
	Issuer    string
	Subject   string
	Audience  string
	ExpiresAt pgtype.Timestamptz
	NotBefore pgtype.Timestamptz
	IssuedAt  pgtype.Timestamptz
}

type TokenDisallowList struct {
	TokenID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// openstats users. table is plural to avoid name collision with pg `user` keyword.
type User struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Slug      string
}

type UserDisplayName struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	UserID      int32
	DisplayName string
}

type UserEmail struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	UserID      int32
	Email       string
	ConfirmedAt pgtype.Timestamptz
}

type UserPassword struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	UserID      int32
	EncodedHash string
}

type UserSlugHistory struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UserID    int32
	Slug      string
}
