// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"database/sql"
	"time"
)

type Achievement struct {
	ID                  int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           sql.NullTime
	GameID              int64
	Slug                string
	Name                string
	Description         string
	ProgressRequirement int64
}

type AchievementProgress struct {
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
	UserID        int64
	AchievementID int64
	Progress      int64
}

type Developer struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Slug      string
}

type DeveloperMember struct {
	ID          int64
	CreatedAt   time.Time
	DeletedAt   sql.NullTime
	UserID      int64
	DeveloperID int64
}

type DeveloperSlug struct {
	ID          int64
	CreatedAt   time.Time
	DeletedAt   sql.NullTime
	DeveloperID int64
	Slug        string
}

type Game struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
	DeveloperID int64
	Slug        string
}

type GameSlug struct {
	ID        int64
	CreatedAt time.Time
	DeletedAt sql.NullTime
	GameID    int64
	Slug      string
}

type User struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Slug      string
}

type UserDisplayName struct {
	ID          int64
	CreatedAt   time.Time
	DeletedAt   sql.NullTime
	UserID      int64
	DisplayName string
}

type UserEmail struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
	UserID      int64
	Email       string
	ConfirmedAt sql.NullTime
}

type UserPassword struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      int64
	EncodedHash string
}

type UserSlug struct {
	ID        int64
	CreatedAt time.Time
	DeletedAt sql.NullTime
	UserID    int64
	Slug      string
}
