// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID                  int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	GameID              int32
	Slug                string
	Name                string
	Description         string
	ProgressRequirement int32
}

type AchievementProgress struct {
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserID        int32
	AchievementID int32
	Progress      int32
}

type DeletedRecord struct {
	ID          uuid.UUID
	DeletedAt   time.Time
	SourceTable string
	SourceID    string
	Data        []byte
}

type Developer struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Slug      string
}

type DeveloperDisplayName struct {
	ID          int32
	CreatedAt   time.Time
	DeveloperID int32
	DisplayName string
}

type DeveloperMember struct {
	ID          int32
	CreatedAt   time.Time
	UserID      int32
	DeveloperID int32
}

type DeveloperSlugHistory struct {
	ID          int32
	CreatedAt   time.Time
	DeveloperID int32
	Slug        string
}

type Game struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeveloperID int32
	Slug        string
}

type GameSession struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	TokenID     pgtype.UUID
	LastPulseAt time.Time
	GameID      int32
	UserID      int32
}

type Token struct {
	ID        uuid.UUID
	Issuer    string
	Subject   string
	Audience  string
	ExpiresAt time.Time
	NotBefore time.Time
	IssuedAt  time.Time
}

type TokenDisallowList struct {
	TokenID   uuid.UUID
	CreatedAt time.Time
}

// openstats users. table is plural to avoid name collision with pg `user` keyword.
type User struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	LookupID  uuid.UUID
	Slug      string
}

type UserDisplayName struct {
	ID          int32
	CreatedAt   time.Time
	UserID      int32
	DisplayName string
}

type UserEmail struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      int32
	Email       string
	ConfirmedAt pgtype.Timestamptz
}

type UserLatestDisplayName struct {
	ID          int32
	CreatedAt   time.Time
	UserID      int32
	DisplayName string
}

type UserPassword struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      int32
	EncodedHash string
}

type UserSlugHistory struct {
	ID        int32
	CreatedAt time.Time
	UserID    int32
	Slug      string
}
