drop table if exists game_session;
drop table if exists token_disallow_list;
drop table if exists token;
drop table if exists achievement_progress;
drop table if exists achievement;
drop trigger if exists game_moddatetime on game;
drop table if exists game;
drop table if exists developer_display_name;
drop table if exists developer_slug_history;
drop table if exists developer_member;
drop trigger if exists developer_moddatetime on developer;
drop table if exists developer;
drop trigger if exists user_password_moddatetime on user_password;
drop table if exists user_password;
drop view if exists user_latest_display_name;
drop table if exists user_display_name;
drop trigger if exists user_email_moddatetime on user_email;
drop table if exists user_email;
drop table if exists user_slug_history;
drop trigger if exists user_moddatetime on users;
drop table if exists users;
drop table if exists deleted_record;
drop function if exists gen_uuid_v7;
drop extension if exists pgcrypto;
drop extension if exists moddatetime;
