// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: developer.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allDevelopers = `-- name: AllDevelopers :many
select id, created_at, updated_at, slug from developer
`

func (q *Queries) AllDevelopers(ctx context.Context) ([]Developer, error) {
	rows, err := q.db.Query(ctx, allDevelopers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Developer
	for rows.Next() {
		var i Developer
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDeveloperBySlug = `-- name: FindDeveloperBySlug :one
select id, created_at, updated_at, slug from developer where slug = $1 limit 1
`

func (q *Queries) FindDeveloperBySlug(ctx context.Context, slug string) (Developer, error) {
	row := q.db.QueryRow(ctx, findDeveloperBySlug, slug)
	var i Developer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const getDeveloperGames = `-- name: GetDeveloperGames :many
select game.slug, game.created_at from game where developer_id = $1
`

type GetDeveloperGamesRow struct {
	Slug      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetDeveloperGames(ctx context.Context, developerID int32) ([]GetDeveloperGamesRow, error) {
	rows, err := q.db.Query(ctx, getDeveloperGames, developerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeveloperGamesRow
	for rows.Next() {
		var i GetDeveloperGamesRow
		if err := rows.Scan(&i.Slug, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeveloperMembers = `-- name: GetDeveloperMembers :many
select u.slug, udn1.display_name, dm.created_at as joined_at
from users u
join developer_member dm on u.id = dm.user_id
left outer join user_display_name udn1 on u.id = udn1.user_id
left outer join user_display_name udn2 on u.id = udn2.user_id and
                                          (udn1.created_at < udn2.created_at or
                                           (udn1.created_at = udn2.created_at and udn1.id < udn2.id))
where dm.developer_id = $1
`

type GetDeveloperMembersRow struct {
	Slug        string
	DisplayName pgtype.Text
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) GetDeveloperMembers(ctx context.Context, developerID int32) ([]GetDeveloperMembersRow, error) {
	rows, err := q.db.Query(ctx, getDeveloperMembers, developerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeveloperMembersRow
	for rows.Next() {
		var i GetDeveloperMembersRow
		if err := rows.Scan(&i.Slug, &i.DisplayName, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
